name = "web_withings"

restart = "unless-stopped"
networks = ["lcars-bridge"]

[setup]
lcars = true

[[volumes.config]]
base = "%base_folder%/addons/web_withings/config/config.toml"
source = "%config_folder%/config.toml"
dest = "/lcars/config/config.toml"

[volumes.web]
"%base_folder%/addons/web_withings/web" = "/lcars/web"