name = "web_withings"
label = "LCARS WebWithings"

version = "1.00"

[docker]
image = "lcars/python:%Y.%m"
folder = 'python'
lcars = true
python = true

[lib]
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon_com.Com"
api = "addon_com.Api"
cache = "sm_storage.WebCache"
