name = "homematic"

restart = "unless-stopped"
networks = ["lcars-bridge"]

[setup]
lcars = true

[[volumes.config]]
base = "%base_folder%/addons/homematic/config/config.toml"
source = "%config_folder%/config.toml"
dest = "/lcars/config/config.toml"

[volumes.base]
"%data_folder%" = "/lcars/data"
"%log_folder%" = "/lcars/log"
"%temp_folder%" = "/lcars/temp"
"%base_folder%/lib" = "/lcars/lib"




