name = "homematic"
label = "LCARS Homematic"
label_short = "Homematic"
icon = "/css/images/homematic.svg"

[docker]
name = "lcars/python:%Y.%m"
folder = 'python'

[lib]
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon.Com"
api = "addon.ApiXML"
