name = "avm"

image = "lcars/python:%Y.%m"
restart = "unless-stopped"
networks = ["lcars-bridge"]

[setup]
lcars = true

[volumes]

# standard Ordner
"%data_folder%" = "/lcars/data"
"%base_folder%/lib" = "/lcars/lib"
"%log_folder%" = "/lcars/log"
"%temp_folder%" = "/lcars/temp"
"%base_folder%/addons/avm/lib" = "/lcars/lib2"


"%base_folder%/addons/avm/src/run.py" = "/lcars/starter/run.py"

"%base_folder%/addons/avm/config" = "/lcars/config"
