name = "shelly"
label = "LCARS Shelly"

[docker]
name = "lcars/python:%Y.%m"
folder = 'python'

[lib]
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon.Com"
api = "addon.Api"
firmware = "addon.Firmwarcheck"
powerhist = "addon.PowerHistory"
