name = "gateway"

image = "lcars/python:%Y.%m"
restart = "unless-stopped"
networks = ["lcars-bridge"]
ports = ['1235:1235']

[setup]
lcars = true

[volumes]
"/var/run/docker.sock" = "/var/run/docker.sock"

# standard Ordner
"%data_folder%" = "/lcars/data"
"%base_folder%/lib" = "/lcars/lib"
"%log_folder%" = "/lcars/log"
"%temp_folder%" = "/lcars/temp"
"%base_folder%/addons/gateway/lib" = "/lcars/lib2"

"%base_folder%/addons/gateway/src/run.py" = "/lcars/starter/run.py"

"%base_folder%/addons/gateway/config/config.toml" = "/lcars/config/config.toml"
"%base_config_folder%/acl.toml" = "/lcars/config/acl.toml"
