name = "gateway"

restart = "unless-stopped"
networks = ["lcars-bridge"]
ports = ['1235:1235']

[setup]
lcars = true

[[volumes.config]]
base = "%base_folder%/addons/gateway/config/config.toml"
source = "%config_folder%/config.toml"
dest = "/lcars/config/config.toml"

[volumes.device]
"/var/run/docker.sock" = "/var/run/docker.sock"
