name = "gateway"
label = "LCARS Gateway"
version = "1.00"

secret = [
    'lcars'
]

[docker]
image = "lcars/python:%Y.%m"
folder = 'python'
lcars = true
python = true


[lib]
docker = "aiodockerlib.Docker"
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon.Com"
cli = "addon.Cli"
