name = "gateway"
label = "LCARS Gateway"

[docker]
name = "lcars/python:%Y.%m"
folder = 'python'

[lib]
docker = "aiodockerlib.Docker"
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon_com.Com"
cli = "addon_com.Cli"
