project = "lcars_supervisor"
version = 1
author = "Frank Holler"
language = "de_DE.utf8"

[pre]
pull = true
folder_ln = ['lib', 'image', 'addons']

[logger]
version = 1
disable_existing_loggers = true
formatters.simple.format = "%(levelname)s: %(message)s"
formatters.detailed.format = "[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"
formatters.detailed.datefmt = "%Y-%m-%dT%H:%M:%S%z"

[logger.formatters.json]
"()" = "loggerlib.MyJSONFormatter"

[logger.formatters.json.fmt_keys]
level = "levelname"
message = "message"
timestamp = "timestamp"
logger = "name"
module = "module"
function = "funcName"
line = "lineno"
thread_name = "threadName"

[logger.loggers.root]
level = "DEBUG"
handlers = ["stdout", "file", "json"]

[logger.handlers.stdout]
class = "logging.StreamHandler"
formatter = "simple"
level = "INFO"
stream = "ext://sys.stdout"

[logger.handlers.file]
class = "logging.handlers.RotatingFileHandler"
formatter = "detailed"
level = "DEBUG"
filename = "%log_folder%/my_log.log"
maxBytes = 100000
backupCount = 3

[logger.handlers.json]
class = "logging.handlers.RotatingFileHandler"
formatter = "json"
level = "DEBUG"
filename = "%log_folder%/my_log.json"
maxBytes = 10000000
backupCount = 9

[pre.requirements]
aioretry = "==5.0.2"
docker = "==7.0.0"
simple_term_menu = "==1.6.4"
rich = "==13.7.1"
pydantic = "==2.7.0"
netaddr = "==1.2.1"

[repositories] # im Moment nur private Quellen
requirejs = "https://git.holler.pro/fholler/requirejs.git"
external_libaries = "https://git.holler.pro/fholler/external_libaries.git"
jQWidgets = "https://git.holler.pro/fholler/jQWidgets.git"
MaterialDesign-SVG = "https://git.holler.pro/fholler/MaterialDesign-SVG.git"
packery = "https://git.holler.pro/fholler/packery.git"

[networks.lcars-bridge]
#type = "bridge"
#subnet = "10.0.0.0/16"
#gateway = "10.0.0.1"
#adapter = "lcars0"
#interface = "eth0"

[networks.local-bridge]
#type = "bridge"
#subnet = "10.1.0.0/16"
#gateway = "10.1.0.1"
#adapter = "lcars1"
#interface = "eth0"

[install]
#apt = ["docker.io", "docker-doc", "docker-compose", "podman-docker", "containerd", "runc"]

[install.apps]
cli = "lcars-cli"

[install.config]
"cli.toml" = 'config/cli/%hostname%/config.toml'
"acl.toml" = 'config/acl.toml'

[[systemd]]
name = "lcars-docker.service"
start = true
enable = false
content = '''
[Unit]
Description=Docker Container Settings aktualiesieren 

[Service]
WorkingDirectory=%base%
ExecStart=%python% %base%/commands/dockerd.py %base% %lcars%
'''
[[systemd]]
name = "lcars-docker.timer"
start = true
enable = true
content = '''
[Unit]
Description=Starten von Docker 

[Timer]
OnCalendar=*-*-* *:00,02,04,06,08,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58:00
RandomizedDelaySec=1m
Persistent=true

[Install]
WantedBy=timers.target
'''

[[systemd]]
name = "lcars-supervisor.service"
start = true
enable = false
content = '''
[Unit]
Description=Supervisor Daemon für Informationen über den Host und ausführen einiger Komanndos 
After=network-online.target
StartLimitIntervalSec=25
StartLimitBurst=5

[Service]
PIDFile=/run/lcars-supervisor.pid
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=3
WorkingDirectory=%base%
ExecStart=%python% %base%/commands/supervisord.py %base% %lcars%

[Install]
WantedBy=multi-user.target
'''
