name = "npm"

image = "jc21/nginx-proxy-manager:latest"
restart = "unless-stopped"
networks = ["local-bridge"]
ports = ['80:80', '443:443', '81:81']

[volumes.base]
"%data_folder%/data" = "/data"
"%data_folder%/letsencrypt" = "/etc/letsencrypt"


