name = "portainer"

image = "portainer/portainer-ce:latest"
restart = "unless-stopped"
ports = ['9000:9000']
networks = ["local-bridge"]

[volumes]
"/var/run/docker.sock" = "/var/run/docker.sock"
"%data_folder%" = "/data"
