name = "web_base"

image = "lcars/python:%Y.%m"
restart = "unless-stopped"
networks = ["lcars-bridge"]
ports = ['1236:1235']

[setup]
lcars = true

[volumes]

# standard Ordner
"%data_folder%" = "/lcars/data"
"%base_folder%/lib" = "/lcars/lib"
"%log_folder%" = "/lcars/log"
"%temp_folder%" = "/lcars/temp"
"%base_folder%/addons/web_base/lib" = "/lcars/lib2"

"%base_folder%/addons/web_base/src/run.py" = "/lcars/starter/run.py"

"%base_folder%/addons/web_base/config/config.toml" = "/lcars/config/config.toml"
"%base_config_folder%/acl.toml" = "/lcars/config/acl.toml"
