name = "web_base"

image = "lcars/python:%Y.%m"
restart = "unless-stopped"
networks = ["lcars-bridge"]
ports = ['1236:1235']

[setup]
lcars = true

[[volumes.config]]
base = "%base_folder%/addons/web_base/config/config.toml"
source = "%config_folder%/config.toml"
dest = "/lcars/config/config.toml"

[[volumes.config]]
source = "%base_config_folder%/acl.toml"
dest = "/lcars/config/acl.toml"

[[volumes.config]]
source = "%base_folder%/addons/web_base/manifest.toml"
dest = "/lcars/config/manifest.toml"

[volumes.base]
"%data_folder%" = "/lcars/data"
"%log_folder%" = "/lcars/log"
"%temp_folder%" = "/lcars/temp"
"%base_folder%/lib" = "/lcars/lib"

[volumes.run]
"%base_folder%/addons/web_base/src/run.py" = "/lcars/starter/run.py"
"%base_folder%/addons/web_base/lib" = "/lcars/lib2"

[volumes.web]
"%base_folder%/addons/web_base/web/index.html" = "/lcars/web/index.html"
"%base_folder%/addons/web_base/web/main.js" = "/lcars/web/main.js"
"%base_folder%/addons/web_base/web/js" = "/lcars/web/js"
"%base_folder%/addons/web_base/web/css" = "/lcars/web/css"
"%git_folder%/requirejs/require.js" = "/lcars/web/js_lib/require.js"
"%git_folder%/external_libaries/jquery/jquery-3.7.0.min.js" = "/lcars/web/js_lib/jquery/jquery-3.7.0.js"
"%git_folder%/external_libaries/SVGInject/svg-inject.js" = "/lcars/web/js_lib/svg-inject.js"
"%git_folder%/jQWidgets/jqwidgets" = "/lcars/web/js_lib/jqwidgets"
"%git_folder%/MaterialDesign-SVG/svg" = "/lcars/web/img/mdi"