name = "web_base"

image = "lcars/python:%Y.%m"
restart = "unless-stopped"
networks = ["lcars-bridge"]
ports = ['1236:80']

[setup]
lcars = true

[volumes]

"%data_folder%" = "/lcars/data"
"%base_folder%/lib" = "/lcars/lib"
"%base_folder%/log" = "/lcars/log"

"%base_folder%/addons/web_base/src/run.py" = "/lcars/starter/run.py"

"%base_folder%/addons/web_base/config" = "/lcars/config"
