name = "web_base"
label = "LCARS WebBase"

[docker]
name = "lcars/python:%Y.%m"
folder = 'python'

[lib]
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon.Com"
static = "addon.Static"
api = "addon.Api"
