name = "withings"

restart = "unless-stopped"
networks = ["lcars-bridge"]

[setup]
lcars = true

[[volumes.config]]
base = "%base_folder%/addons/withings/config/config.toml"
source = "%config_folder%/config.toml"
dest = "/lcars/config/config.toml"

[volumes.run]
"%base_folder%/addons/withings/src/update.py" = "/lcars/starter/update.py"
