name = "web_router"
label = "LCARS WebRouter"

[docker]
name = "lcars/python:%Y.%m"
folder = 'python'

[lib]
web = "httplib.HTTP"
web_l = "httplib.ClientLocal"
com = "addon_com.Com"
api = "addon_com.Api"
